print("Hello world")
Naam = input("What is your name?\n")
Lengte = len(Naam)
print(f'Your Name is {Naam} and is {Lengte} letters long\n')
print("Welcome to Band name Generator")
City = input("Where do you live\n")
petName = input("What is the name of your Pet\n")
print(f"Your generated band name is {City} {petName}")
print("Erik houd van geld")